New server implementation and bugfixes (streaming branch)
sanic-org/sanic pull request #1876
Opened 2020-06-21 12:46 UTC by Tronic

Moved from https://github.com/huge-success/sanic/pull/1791

A plain Python reimplementation of Sanic's built-in server and related restructuring also in ASGI backend and in response handling. Includes first-class support for streaming, improved performance and better ground for further development.

By the sheer volume of it, it also brings some breaking changes like the removal of custom protocol support but typical applications that do not do anything special with the server's internals should remain mostly unaffected.

Installation:
```
pip install git+https://github.com/huge-success/sanic@streaming
```

Issues of current git master, resolved in this:
Fix #1653
Fix #1722
Fix #1730
Fix #1785
Fix #1790
Fix #1804
Fix #1875

2020-09-27 13:23 UTC, ahopkins commented
I am sure there are already a number of conflicts here. Before it gets too wildly out of sync, do you want to try to do a rebase (or merge, not picky) to bring this back current to `master`? I am thinking that I want to keep this at the forefront so it is ready to merge asap after December's LTS, with some of the other major changes that are waiting to follow after this.

2020-09-28 06:52 UTC, Tronic commented
@ahopkins Help with that would be nice. I'm busy with work and academia pretty much 7 days every week until Nov/Dec, also you are probably better familiar with all the patches merged to master meanwhile. I believe it would be easier to merge them to this branch than rebase the whole thing.

2020-09-28 20:21 UTC, ahopkins commented
@Tronic. Sounds good. :metal: 

After the release this week ...

2020-10-24 19:46 UTC, ahopkins commented
I merged in recent changes to master. I did not spend any time on the tests. Looks like about 12 need some attention. I can take a look at these this week.

2020-12-30 09:36 UTC, ahopkins commented
@huge-success/sanic-core-devs Please take a look at this one. I'd like to get this merged by the end of the weekend. Even if it is not 100% perfect and release worthy, I want to get this merged because of the large number of changes that it entails. Having it merged into `master` will allow us to continue making other PRs without resolving too many conflicts. Release it not set until March, but I want to make sure there is **plenty** of time to test this in `master`.

2020-12-30 19:53 UTC, ahopkins commented
This pull request has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/new-streaming-api-and-other-major-changes/518/15

2021-01-05 12:19 UTC, ahopkins commented
This pull request has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/2021-release-managers-and-updates/781/1

2021-01-10 18:22 UTC, ahopkins requested changes
I'll handle these. When done, I want to merge. @sanic-org/sanic-core-devs any other thoughts before I do so?

2021-01-10 18:22 UTC, ahopkins commented on sanic/asgi.py
> +            instance.request_body = True  # FIXME: Use more_body?
Needs resolution.

2021-01-10 18:22 UTC, ahopkins commented on sanic/request.py
> +        self, response=None, *, status=200, headers=None, content_type=None
Need to take a closer look to confirm that this is actually the correct place for this.

2021-01-10 18:22 UTC, ahopkins commented on sanic/response.py
> +        # TODO: Make a blacklist set of header names and then filter with that
Resolve.

2021-01-10 18:22 UTC, ahopkins commented on sanic/response.py
> +        chunked="deprecated",
Remove?

2021-01-10 18:22 UTC, ahopkins commented on sanic/response.py
> +        with memoryview(body):
Let's benchmark this.

2021-01-10 22:29 UTC, ahopkins approved these changes

2021-01-10 22:45 UTC, merged

2021-01-19 03:00 UTC, ashleysommer commented
Just looking over these merged changes now, to learn how Sanic works at a low level now.

I have noticed it looks like there is a possibility for the Request Middleware to run twice on a request.
Both the `app.handle_request` and `app.handle_exception` methods execute the Request middleware.

If the main handler encounters an exception _after_ running the middleware, then the exception handler will execute and run the request middleware _again_.

2021-01-19 03:25 UTC, ahopkins commented
Yeah. That is the purpose of it.  I think eventually I want to get rid of it and not have to carry that state trigger (there is not a similar one for response).

2021-02-09 11:57 UTC, ahopkins commented
This pull request has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/highly-different-cpu-usage-when-proxying-m2tp-udp-unicast-stream-to-a-streamed-sanic-response/795/10