[20.12LTS] Remove prefix from websocket handler name
sanic-org/sanic pull request #2021
Opened 2021-02-05 15:12 UTC by laggardkernel

Formerly try to open for master branch GH-2020. Cause the Router is overhauled open pr for 20.12LTS.

---

Remove the websocket prefix `websocket_handler_` introduced in
761eef7. Makes `url_for()` unable to find the corresponding ws route for non-bp websocket view.

2021-02-07 12:58 UTC, laggardkernel commented
During reading the source code. I've found inconsistent behaviors among route storing of normal http handler and websocket, static file handlers.

Firstly, the ways used to indicate a websocket handler and static file handler are different.

`_static_` is prepend into `name` param from `Sanic.static(name="static")`. It's the same `name` param passed to  `Router._add(..., name)`. The `_static_` is used as a flag in `Router._add()` to indicate current handler being registered is a static file handler, not used in anywhere else.

`websocket.is_websocket` is set in `Sanic.websocket()`, and the flag is only used in `Sanic.handle_request()`.

Secondly, the ways to pass blueprint names of http handler, websocket handler, static file handler, to be used in `Router._add()` are different.

Formerly, only `handler.__blueprintname__` is used. The bp name is prepended with handler name as the route name (key used in `Router.routes_name`, `Router.routes_static_files`) in `Router._add()`.

For blueprint websocket handler (`Blueprint.websocket()`), not the original handler but a handler wrapper is passed to `Router._add()`. (Check `Sanic._websocket_handler()` and `static._static_request_handler()`) Seems later contributors (938c49b) didn't copy the `__blueprintname__` attr to the handler wrapper. They chose to pass `bp_name + handler` to `Router._add()` directly. Similar thing happens on static file handler `Blueprint.static()` registration.

2021-02-08 01:37 UTC, ahopkins commented
The new branch I am working on does not use any special prefixes for static or websockets. Also, there is a change to how routes are named in general. But I'll leave rhat discussion for #2010.

2021-02-12 10:39 UTC, ahopkins commented
Since we are merging this into the LTS, I am hesitant to cause breaking changes. While I agree there is the issue with `url_for`, potentialling the name with the prefix are in use in some applications. Therefore I am thinking that we probably need to add support for both with and without the handler here.

2021-02-15 12:34 UTC, ahopkins requested changes
Needs to handle fetching routes with and without so that it is not a breaking change.

2021-03-01 12:47 UTC, sjsadowski commented
@laggardkernel are you able to implement @ahoplins request?

2021-03-01 14:31 UTC, laggardkernel commented
@sjsadowski Just pushed an update with backward support, in case anyone find the bug and use `url_for("websocket_handler_<view_name>")` in his code.

2021-03-01 14:50 UTC, ahopkins requested changes
Looks great @laggardkernel. Can you add a test case to `test_url_building.py` for both cases?

Something like this. Also, one for Blueprints.

```python
def test_url_for_with_websocket_handlers(app):
    @app.websocket("/ws")
    async def my_handler(...):
        ...
    
    assert app.url_for("my_handler") = "..."
    assert app.url_for("websocket_handler_my_handler") = "..."
```

2021-03-01 15:09 UTC, ahopkins approved these changes

2021-03-01 15:16 UTC, laggardkernel commented
@ahopkins Thanks for pointing out the correct place to add the test. I've updated and squashed the commits.

2021-03-01 15:18 UTC, ahopkins commented
Approved and will merge when Travis is done 🐢

I'll get this pushed out to the LTS tonight.

2021-03-01 15:18 UTC, ahopkins commented
Thanks again for this.

2021-03-14 08:13 UTC, ahopkins commented
@laggardkernel Can you address the CI issues? Linting issues can be fixed by running:

```
make pretty
```

2021-03-14 08:50 UTC, laggardkernel commented
@ahopkins Sorry, fixed and passed the CI.

2021-03-14 18:32 UTC, ahopkins approved these changes

2021-03-14 18:33 UTC, merged