fix?: recursion error on Sanic subclass initialisation
sanic-org/sanic pull request #2072
Opened 2021-03-20 16:56 UTC by artcg

Needs someone to take a look at it, not super familiar with `__new__`,

but it seems to fix the error and work as expected

2021-03-20 17:23 UTC, artcg commented
Would also add a test case for this if subclassing `Sanic` is something that is officially supported...

2021-03-21 01:12 UTC, ahopkins commented
@artcg Thanks. Can you add a test? You can drop it at the end of `test_app.py`. It is something that I know is done, so we should have that in the test suite.

2021-03-21 01:27 UTC, ahopkins requested changes
This works and makes sense. Nice catch.

But, I want to play with this a little more because I think it might not yet cover all the edge cases.

Let's add the test, and I will swing back on this tomorrow with some more thoughts.

2021-03-21 01:27 UTC, ahopkins commented on sanic/base.py
>              for base in bases:
Since we no longer need the comprehension, no need to have `bases` as a variable.

```python
for base in BaseSanic.__bases__:
```

2021-03-21 01:39 UTC, artcg commented
Is it an optimisation not just to define `BaseSanic.__init__ ` directly?

2021-03-21 07:37 UTC, ahopkins commented
I am going to push a change to this branch and merge it to get rid of the metaclass here.

2021-03-21 07:44 UTC, ahopkins commented
I am pushing a change directly to this branch to remove the metaclass.

2021-03-21 07:46 UTC, ahopkins approved these changes

2021-03-21 08:09 UTC, merged