wip: deprecate abort
sanic-org/sanic pull request #2077
Opened 2021-03-21 13:22 UTC by artcg

non-internal changes:

- `SanicException` allows to be constructed without arguments

this is more in-line with other builtin python Exceptions, I was surprised that "message" was required before, and think users would be too.

- add_status_code decorator is removed straight away

I didn't think a warning was necessary here since really nobody should be using this, but can add if desired...

- abort now raises SanicException with status_code instead of the appropriate subtype

Since abort is slated for removal I am not too worried about this, but can add back old behaviour during transition also if it's desired

2021-03-21 13:30 UTC, ahopkins requested changes
Looks good. I am fine with these changes/deprecations as is.

Let's add a test case to catch the `abort` warning. If you `grep` I am sure you can find some other instances to copy.

Also, one tests that implement both the fallback message and a custom message. Looks like custom `status_code` is already covered.

2021-03-21 14:22 UTC, artcg commented
Sounds good,

btw this is completely wrong place to discuss but just curious, whats the plan with sanic-routing? Keep it as a separate repo to sanic or bring it back in? Is the disconnect between versioning for sanic and sanic-routing a feature?

2021-03-21 14:52 UTC, ahopkins commented
There is an ongoing conversation. It has not been decided. There might be some utility to keeping it seperate, but I suspect we will have a definitive answer by the Summer.

2021-03-21 15:16 UTC, ahopkins requested changes
One more change.

2021-03-21 15:16 UTC, ahopkins commented on sanic/exceptions.py
> +    def __init__(self, message=None, status_code=None, quiet=None):
Can you add some type annotations here?

2021-03-21 15:19 UTC, miss85246 commented
looks interesting

2021-04-05 11:21 UTC, ahopkins requested changes

2021-04-05 11:21 UTC, ahopkins commented on sanic/exceptions.py
> +            # These are stored as bytes in the STATUS_CODES dict
You can remove this comment. It is not necessary.

2021-04-05 14:53 UTC, ahopkins approved these changes

2021-04-05 15:01 UTC, merged

2021-09-06 09:50 UTC, dnikolayev commented
Guys, you're crazy :)
in 21.3 the decorator exists(as in all previous since even 0.6 or 0.8.3) in 21.6 - no :)
No deprecation warning in the documentation  :(

2021-09-06 11:07 UTC, ahopkins commented
> Guys, you're crazy :)
> in 21.3 the decorator exists(as in all previous since even 0.6 or 0.8.3) in 21.6 - no :)
> No deprecation warning in the documentation :(

What decorator `@add_status_code`?

2021-09-09 07:44 UTC, dnikolayev commented
Sorry, but I was using this decorator for ages :)
So, I had questions about the backward compatibility of [webargs-sanic](https://github.com/EndurantDevs/webargs-sanic). 
For instance, I know about the 0.8 or 18.12 usages still with newer and older form-data validation.
Now all is good with Sanic 0.8.3 to 21.6.2: https://app.travis-ci.com/github/EndurantDevs/webargs-sanic/builds/237030388

Thanks!

P.s. The only thing is harder to support now - changes in the testing part, but I will figure out something (sanic-testing only from 21th versions, etc.)

2021-09-13 10:22 UTC, ahopkins commented
@dnikolayev Thank you very much for bringing this up. We are really trying to narrow in on both the public and private API to get the project (hopefully) to a "stable" classifier in the next LTS. I have been trying very hard to make sure we stick to backwards compat support thru at least a couple versions for any deprecations. I apologize if this one slipped through the cracks.