Avoid dangling sockets by using abort() instead of close()
sanic-org/sanic pull request #2191
Opened 2021-07-10 22:02 UTC by DirtyHairy

Fixes #2190

2021-07-11 12:22 UTC, Tronic approved these changes
Seems acceptable, considering that this is force closing only after graceful shutdown timeout.

2021-07-11 19:31 UTC, ahopkins commented
I am not sure this is _always_  the desirable outcome.

`HttpProtocol.close()` is called in the following cases:

1. At the end of `connection_task`
1. When `close_if_idle()` is called (in graceful server shutdown `serve()` before the timeout)
1. At the completion of attempting a graceful shutdown
1. When `data_received` is called with falsey value

I think it might be okay to (1) add some sort of a timeout as you suggested in #2190, and/or (2) add an `abort=True` flag for the cases where we know it is safe.

It seems more like we need to look deeper into #2189 to see why that task is being terminated and we are not waiting for it to complete.

I think 1 and 3 are probably safe for `abort()`.

Perhaps another alternative is to run the `close_if_idle()` loop once again after the `GRACEFUL_SHUTDOWN_TIMEOUT`, before attempting an `abort()`. Or, just moving `close_if_idle()` to after timeout in general. Presumably, this would provide time for them to close on their own.

2021-07-11 20:28 UTC, ahopkins requested changes
`pause`

2021-08-08 18:50 UTC, ahopkins commented
@DirtyHairy Are you looking further into this?

2021-08-08 19:25 UTC, DirtyHairy commented
@ahopkins Not at the moment, sorry. I don't know the code base well enough for a quick fix other than this PR (your criticism of which is valid), and I don't have time to dig into this deeper, in particular since I switched my current project to aiohttp and don't have another project using Sanic atm.

2021-09-01 05:14 UTC, ahopkins commented
Replaced by #2231

2021-09-01 05:14 UTC, closed without merging