Better error handling for malformed urls
sanic-org/sanic pull request #2395
Opened 2022-02-01 21:49 UTC by sjsadowski

Closes #2394

2022-02-02 15:15 UTC, Tronic commented
@sjsadowski Can you add tests for 100 % patch coverage?

2022-02-02 16:20 UTC, prryplatypus commented on sanic/request.py
> +                f"URL is invalid or malformed"
```suggestion
                "URL is invalid or malformed"
```

2022-02-02 17:38 UTC, sjsadowski commented
> @sjsadowski Can you add tests for 100 % patch coverage?

There was a test added for this in test_bad_request.py

2022-02-02 18:47 UTC, ahopkins requested changes
Looks like this branches off #2389 so this PR is blocked.

2022-02-02 18:56 UTC, sjsadowski commented
@ahopkins my bad. I can reimplement off main.

2022-02-02 19:04 UTC, ahopkins commented
> @ahopkins my bad. I can reimplement off main.

no need. We'll just do them in order.

2022-02-03 12:00 UTC, sjsadowski commented
Closing because I need to rethink #2389 on which this is dependent.

2022-02-03 12:00 UTC, closed without merging