Document middleware `on_request` and `on_response`
sanic-org/sanic pull request #2398
Opened 2022-02-11 20:12 UTC by Bluenix2

## Summary

When looking through the documentation I was unable to find these two methods, without docstrings these methods do not show up in the autogenerated documentation.

---

There's not much more to say about this change.

2022-02-11 22:35 UTC, prryplatypus submitted a review, later dismissed
LGTM. Thank you!

2022-02-12 00:34 UTC, prryplatypus submitted a review, later dismissed

2022-02-12 01:14 UTC, Bluenix2 commented
I don't understand how any of my changes correlate to the tests failing.

2022-02-12 17:32 UTC, ahopkins requested changes

2022-02-12 17:32 UTC, ahopkins commented on sanic/mixins/middleware.py
> +        is handled or a response sent. Can either be called as
"or after a response is created"

2022-02-12 17:32 UTC, ahopkins commented on sanic/mixins/middleware.py
> +        """Register a middleware to be called before a response is sent.
"after a response is created"

2022-02-13 08:04 UTC, ahopkins approved these changes
Thanks for the addition.

2022-02-13 18:47 UTC, prryplatypus approved these changes

2022-02-13 19:08 UTC, merged