Fix for running in pythonw
sanic-org/sanic pull request #2448
Opened 2022-05-04 11:43 UTC by timmo001

Running sanic server on windows and on `pythonw.exe` causes the app to silently crash due to `sys.stdout` being None.

<img width="1116" alt="NVIDIA_Share_2022-05-04_12-36-03" src="https://user-images.githubusercontent.com/28114703/166674580-3493a984-5606-4c8d-bf17-faaec09ca07e.png">
 

This adds a check for stdout. The rest of the server then continues to function normally.

2022-05-12 16:36 UTC, ahopkins requested changes

2022-05-12 16:36 UTC, ahopkins commented on sanic/mixins/runner.py
> +        if sys.stdout and sys.stdout.isatty() and not self.state.is_debug:
For some reason GH is not giving me the option to create a suggestion here... :thinking: 

Nevetheless, can you change this whole block like this:

```python
        if not self.state.is_debug:
            message = (
                "Sanic is running in PRODUCTION mode. Consider using "
                "'--debug' or '--dev' while actively developing your "
                "application."
            )
            if sys.stdout and sys.stdout.isatty():
                message = "".join([Colors.YELLOW, message, Colors.END])
            error_logger.warning(message)
```

2022-05-12 16:37 UTC, ahopkins commented on sanic/mixins/runner.py
> +        if sys.stdout and sys.stdout.isatty() and not self.state.is_debug:
At some point we can abstract some of the color stuff, but for now this at least keeps the message still populating.

2022-05-12 17:45 UTC, ahopkins commented
@timmo001 I am sorry, in my head I was looking at the original logic thinking that it was wrong. That is why I suggested the change. But, it was correct. I reverted the PR back to your original suggestion. Let's pretend I never suggested that to begin with :laughing: 

Thanks for catching this for us.

2022-05-12 17:46 UTC, ahopkins approved these changes

2022-05-12 17:47 UTC, ahopkins requested changes
Here's a suggestion that _ACTUALLY_ makes sense...

There are a few more places that follow a similar pattern. Perhaps you can add the same change:

```
sanic/mixins/runner.py:427:        if sys.stdout and sys.stdout.isatty() and not self.state.is_debug:
sanic/mixins/runner.py:618:                if sys.stdout.isatty():
sanic/mixins/runner.py:659:                        if sys.stdout.isatty():
sanic/log.py:86:    if sys.stdout.isatty():
sanic/application/motd.py:39:        motd_class = MOTDTTY if sys.stdout.isatty() else MOTDBasic
sanic/application/logo.py:47:        if sys.stdout.isatty()
```

2022-05-24 06:06 UTC, ahopkins submitted a review, later dismissed

2022-06-01 23:03 UTC, timmo001 commented
Update on this? I see its been approved but the checks are failing.

I've rebased, but this requires an approver to run

2022-06-10 22:39 UTC, timmo001 commented
I've rebased, but this requires an approver to run

2022-06-14 21:58 UTC, timmo001 commented
Fixed lint, needs approval

2022-06-15 04:50 UTC, ahopkins approved these changes

2022-06-16 19:57 UTC, ahopkins approved these changes

2022-06-19 01:45 UTC, ahopkins submitted a review, later dismissed

2022-06-19 11:48 UTC, merged

2022-06-25 12:56 UTC, timmo001 commented
Schedule for the next release?

2022-06-26 07:37 UTC, ahopkins commented
Should be this week.