Fix Docker image publish GitHub Action
sanic-org/sanic pull request #2799
Opened 2023-08-13 05:11 UTC by ChihweiLHBird

It stopped working in the last release due to [the name change of PyPI publish action](https://github.com/sanic-org/sanic/pull/2797/files#diff-76272691d414169ea851c113f750e3f9638354d7e4473ad7131d69ec1fcea201L1).

2023-08-13 06:15 UTC, ChihweiLHBird commented
Not sure why the docs lint CI is broken, but it looks irrelevant to this change. It runs well on my local machine with the same `pip`, `wheel`, and `setuptools` versions.

It seems to be related to [patch version does not appear in the requirement string of `autodocsumm` package,](https://github.com/Chilipp/autodocsumm/blob/master/pyproject.toml#L34) but the weird part is it never complain this elsewhere.
```
    × python setup.py egg_info did not run successfully.
  Collecting aioquic
    │ exit code: 1
    ╰─> [3 lines of output]
        error in autodocsumm setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; .* suffix can only be used with `==` or `!=` operators
            Sphinx>=2.2.*
                  ~~~~~~^
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
```

2023-08-13 07:23 UTC, ahopkins requested changes
What's the purpose of this?

2023-08-13 07:40 UTC, ChihweiLHBird commented
> What's the purpose of this?

For making this action works. Currently the trigger is "when a workflow named `Publish Artifacts` is completed", since the `Publish Artifacts` workflow was renamed to `Upload Python Package`, we will need to change this trigger accordingly.

2023-08-23 17:51 UTC, prryplatypus commented
This PR will be superseded by #2808 , as the whole actions flow has been reworked :D

2023-08-26 20:39 UTC, ChihweiLHBird commented
Appreciated it! @prryplatypus 

@ahopkins I think this is ready to be reviewed.

2023-08-26 20:39 UTC, closed without merging